name: Jest tests

on: [ push, pull_request ]

jobs:
  unit_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Set up node
        uses: actions/setup-node@v1
      - run: npm install
      - name: Run tests
        run: npm test